#!/bin/bash

jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git
nbdime extensions --enable

jupyter labextension install jupyterlab-drawio

jupyter labextension install jupyterlab-jupytext
jupyter labextension install @jupyterlab/latex
jupyter labextension install @jupyterlab/geojson-extension

jupyter serverextension enable --py jupyterlab_zenodo
jupyter labextension install @chameleoncloud/jupyterlab_zenodo
